<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{a2110135-111d-486c-a926-541f4e1370f7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Demo : FB_Demo;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Demo();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>